countries/config/routes.rb
Rails.application.routes.draw do
    root 'welcome#index'
    get '/welcome', to: 'welcome#index'

    resources :landmarks

    resources :countries do
      resources :landmarks, only: [:create, :new, :show]
    end
end

countries/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

countries/app/models/country.rb
class Country < ApplicationRecord
  has_many :landmarks
end

countries/app/models/landmark.rb
class Landmark < ApplicationRecord
  belongs_to :country
end

countries/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

countries/app/controllers/countries_controller.rb
class CountriesController < ApplicationController
    before_action :set_country, only: [:show, :edit, :update, :destroy]

  def index
    @countries = Country.all # all the countries
  end

  def show
    @country = Country.find(params[:id]) #one country
    @landmarks = @country.landmarks #one country' landmarks
  end

  def new
    @country = Country.new
    # @landmark = @country.landmarks.new
  end

  def create
    @country = Country.new(country_params)
    # @landmark = @country.landmark.new(landmark_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Post was successfully
          updated.' }
        else
          format.html { render :edit }
        end
      end
  end

  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Post was successfully
        destroy' }
      format.json { head :no_content }
    end
  end

  private
  def set_country
      @country = Country.find(params[:id])
  end

  def country_params
      params.require(:country).permit(:name, :capital, :continent)
  end

end

countries/app/controllers/landmarks_controller.rb
class LandmarksController < ApplicationController
  before_action :set_landmark, only: [:show, :edit, :update, :destroy]

  def index
    @landmarks = Landmark.all # all the landmarks
  end

  def show
    # @country = Country.find(params[:id]) #one country
    @landmark = Landmark.find(params[:id]) #one country' landmarks
    @country = @landmark.country
  end

  def new
    @landmark = Landmark.new
    # @landmark = @country.landmarks.new
  end

  def create
    @landmark = Landmark.new(landmark_params)
    # @landmark = @country.landmarks.new(landmark_params)
    # @landmark = Landmark.find(params[:country_id])

    respond_to do |format|
      if @landmark.save
        format.html { redirect_to @landmark, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @landmark }
      else
        format.html { render :new }
        format.json { render json: @landmark.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @landmark.update(landmark_params)
        format.html { redirect_to @landmark, notice: 'Post was successfully
          updated.' }
        else
          format.html { render :edit }
        end
      end
  end

  def destroy
    @landmark.destroy
    respond_to do |format|
      format.html { redirect_to landmarks_url, notice: 'Post was successfully
        destroy' }
      format.json { head :no_content }
    end
  end

  private
  def set_landmark
      @landmark = Landmark.find(params[:id])
  end

  def landmark_params
      params.require(:landmark).permit(:name, :description, :photo, :country_id)
  end



end

countries/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

countries/app/helpers/application_helper.rb
module ApplicationHelper
end

countries/app/helpers/countries_helper.rb
module CountriesHelper
end

countries/app/helpers/landmarks_helper.rb
module LandmarksHelper
end

countries/app/helpers/welcome_helper.rb
module WelcomeHelper
end

countries/app/views/countries/_form.html.erb
<%= form_for(@country) do |f| %>

<div class="createCountry">
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
</div>

<div class="createCountry">
  <%= f.label :capital %><br>
  <%= f.text_area :capital %><br>
</div>

<div class="createCountry">
  <%= f.label :continent %><br>
  <%= f.text_area :continent %><br>
</div>

<div class="submitCountry">
  <%= f.submit %><br>
</div>

<% end %>

countries/app/views/countries/edit.html.erb
<h1>Edit A Country</h1>

<%= render partial: 'form' %>

countries/app/views/countries/index.html.erb
<h1>Countries</h1>
<p>Select a country to see some of the world's most
breathtaking landmarks</p>
<div class="country">
  <ol>

  <% @countries.each do |country| %>
    <!-- <li><%= country.capital %></li>
    <li><%= country.continent %></li> -->
  <li><%= link_to country.name, country_path(country) %></li><br>
  <% end %>

  </ol>

  <p><%= link_to "Create New Country", new_country_path %></p>

  <p><%= link_to "Create New Landmark", new_landmark_path(@country) %></p>

  <p><%= link_to "Landmarks", landmarks_path %></p>

  <p><%= link_to "Home", welcome_path %></p>
</div>

countries/app/views/countries/new.html.erb
<h1>Add a New Country </h1>

<%= render partial: 'form' %>

countries/app/views/countries/show.html.erb
<h1><%= @country.name %></h1>

<p>Capital: <%= @country.capital %></p>
<p>Continent: <%= @country.continent %> </p>

<ul>
  <% @landmarks.each do |landmark| %>
    <li><%= link_to landmark.name, landmark_path(landmark) %></li>


  <% end %>
</ul>

<%= link_to "All Countries", countries_path %>

<%= link_to 'Edit Country!', edit_country_path %>
<%= link_to 'Delete Country', country_path(@country), method: :delete,
    data: { confirm: "Are you sure you want to delete #{@country.name}?" } %>

countries/app/views/landmarks/_form.html.erb
<%= form_for([@country, @landmark]) do |f| %>

<p>
Before you create a new landmark, please create a
<%= link_to "New Country", new_country_path %><br>
If you did, here's your cocktail 🍸🍹
</p>

<div class="form">
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
</div>

<div class="form">
  <%= f.label :description %><br>
  <%= f.text_area :description %><br>
</div>

<div class="form">
  <%= f.label :photo %><br>
  <%= f.text_field :photo, placeholder:"insert your url🙃" %><br>
</div>

<div class="form">
<%= f.collection_select(:country_id, Country.all, :id, :name ) %><br>
</div>

<div id="submit">
  <%= f.submit %><br>
</div>

<div id=countries>
<%= link_to "Countries", countries_path %><br>
</div>

<% end %>

countries/app/views/landmarks/edit.html.erb
<h1>Edit A Landmark</h1>

<%= render partial: 'form' %>

countries/app/views/landmarks/index.html.erb
<h1>Landmarks</h1>
<p>Select one, and be prepared to be amazedddd😎😆</p>
<div class="country">
  <ol>

  <% @landmarks.each do |landmark| %>

  <li><%= link_to landmark.name, landmark_path(landmark) %></li><br>
  <% end %>

  </ol>

  <p><%= link_to "Create New Landmark", new_landmark_path(@country) %></p>

  <p><%= link_to "Countries", countries_path %></p>

  <p><%= link_to "Home", welcome_path %></p>

</div>

countries/app/views/landmarks/new.html.erb
<h1>Add A New Landmark </h1>

<%= render partial: 'form' %>

countries/app/views/landmarks/show.html.erb
<h1><%= @landmark.name %></h1>

<ul>
    <img src="<%= @landmark.photo%>" style="width:60%;height:40%;"/>
    <li>Country: <%= @country.name %></li>
    <li>Continent: <%= @country.continent %> </li>
    <li><%= @landmark.description %></li>


</ul>

<%= link_to "All Landmarks", landmarks_path %>
<p><%= link_to "Create New Landmark", new_landmark_path(@country) %></p>



<%= link_to 'Edit Landmark!', edit_landmark_path %>
<%= link_to 'Delete Landmark', landmark_path(@landmark), method: :delete,
    data: { confirm: "Are you sure you want to delete #{@landmark.name}?" } %>

countries/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Countries</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

countries/app/views/welcome/index.html.erb
<h1>Greetings, welcome Landmarki</h1>

<p>Please select a country to see their landmarks</p>


<%= link_to "Countries", countries_path %>